<?php 

	$con = mysqli_connect('localhost:3306', "volneiap_frases", 'wolney007');
	mysqli_select_db($con, 'volneiap_frases');
	
	ini_set('default_charset','UTF-8');
	mysqli_set_charset($con, "utf8");
	
	$sql = "CREATE TABLE `categorias` (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `categoria` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	  PRIMARY KEY (`id`)
	) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci";
	
	mysqli_query($con, $sql);
	
	$sql = "insert  into `categorias`(`id`,`categoria`) values 
	(1,'Variadas'),
	(2,'Motivacionais'),
	(3,'Humor'),
	(4,'Depressão'),
	(5,'Deus'),
	(6,'Heróis'),
	(7,'Dinheiro'),
	(8,'Ânimo'),
	(9,'Estudos'),
	(10,'Amor'),
	(11,'Amizade'),
	(12,'Namoro/Casamento'),
	(13,'Perdão')";

	mysqli_query($con, $sql);
	
	$sql = "CREATE TABLE `frases` (
		  `id` int(11) NOT NULL AUTO_INCREMENT,
		  `texto` text COLLATE utf8_unicode_ci DEFAULT NULL,
		  `categoria_id` int(11) DEFAULT NULL,
		  PRIMARY KEY (`id`),
		  KEY `fk_categoria` (`categoria_id`),
		  CONSTRAINT `fk_categoria` FOREIGN KEY (`categoria_id`) REFERENCES `categorias` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
		) ENGINE=InnoDB AUTO_INCREMENT=131 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci";
	
	mysqli_query($con, $sql);
	
	$sql = "insert  into `frases`(`id`,`texto`,`categoria_id`) values 
(1,'Acredite em si mesmo e todo o resto cairá no lugar.',1),
(2,'O sucesso é a soma de pequenos esforços repetidos dia após dia.',1),
(3,'Nada é impossível, a palavra em si diz \"eu sou possível\".',1),
(4,'O otimismo é a fé em ação. Nada se pode levar a efeito sem otimismo.',1),
(5,'A persistência é o caminho do êxito.',1),
(6,'Se você quer alcançar grandes coisas, faça grandes sacrifícios.',1),
(7,'Você nunca sabe que resultados virão da sua ação. Mas se você não fizer nada, não existirão resultados.',1),
(8,'O fracasso é apenas a oportunidade de começar de novo, desta vez de forma mais inteligente.',1),
(9,'Acredite em seus sonhos e eles podem se tornar realidade.',1),
(10,'O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso. Se você ama o que faz, você será bem-sucedido.',1),
(11,'O amor verdadeiro é aquele que permanece mesmo quando todas as circunstâncias parecem contrárias.',10),
(12,'Um relacionamento feliz é construído com base na confiança, respeito e comunicação.',10),
(13,'Amar é encontrar a felicidade nos braços de outra pessoa.',10),
(14,'O amor é um sentimento que cresce quando o compartilhamos.',10),
(15,'No amor, não existe lugar para o egoísmo. É preciso dar tanto quanto receber.',10),
(16,'O verdadeiro amor é capaz de superar qualquer obstáculo que surgir no caminho.',10),
(17,'Amar é enxergar a beleza única e especial em cada pequeno gesto do seu parceiro.',10),
(18,'O amor é uma parceria, onde ambos crescem e evoluem juntos.',10),
(19,'O amor verdadeiro não conhece distância, ele une corações onde quer que estejam.',10),
(20,'O amor não é perfeito, mas é nas imperfeições que encontramos a verdadeira essência do relacionamento.',10),
(21,'Perdoar não significa esquecer, mas sim libertar-se do peso do ressentimento.',13),
(22,'O perdão é um ato de amor próprio, é dar a si mesmo a oportunidade de seguir em frente.',13),
(23,'Perdoar não é admitir que o que aconteceu foi certo, mas sim escolher não carregar mais o peso do passado.',13),
(24,'O perdão é um presente que você dá a si mesmo, permitindo-se viver em paz.',13),
(25,'Quando perdoamos, abrimos espaço para o amor e a cura em nossas vidas.',13),
(26,'Perdoar é uma escolha corajosa, pois liberta-nos das correntes do ressentimento.',13),
(27,'O perdão é a chave que abre a porta para um futuro cheio de paz e felicidade.',13),
(28,'O perdão não é um sinal de fraqueza, mas sim um gesto de força interior.',13),
(29,'Perdoar é reconhecer nossa humanidade compartilhada e a capacidade de errar.',13),
(30,'O perdão não muda o passado, mas transforma o futuro.',13),
(31,'Não leve a vida tão a sério, afinal, você não vai sair vivo dela mesmo!',3),
(32,'A vida é curta, sorria enquanto ainda tem dentes!',3),
(33,'Se planos A, B e C falharem, relaxe e aproveite o alfabeto inteiro!',3),
(34,'Não se preocupe com os haters, eles são apenas fãs secretos que têm medo de se revelar!',3),
(35,'Você é mais forte do que pensa, especialmente quando a bateria do celular está acabando!',3),
(36,'Acredite em si mesmo, mas não tão forte a ponto de quebrar o espelho!',3),
(37,'Não adianta chorar sobre o leite derramado, mas um sorvete derretido é outra história!',3),
(38,'Seja a pessoa que seu cachorro acredita que você é - alguém que sempre tem petiscos!',3),
(39,'A vida é uma montanha-russa, então amarre o cinto de segurança e grite \"woohoo\"!',3),
(40,'Você não pode comprar a felicidade, mas pode comprar pizza, que é quase a mesma coisa!',3),
(41,'Acredite em si mesmo e no poder dos seus sonhos. Você é capaz de coisas grandiosas!',2),
(42,'Nunca é tarde demais para ser quem você quer ser. Acredite em si mesmo e siga em frente!',2),
(43,'Seja a mudança que você deseja ver no mundo. Pequenas ações podem causar grandes impactos!',2),
(44,'O sucesso é a soma de pequenas ações repetidas todos os dias. Mantenha-se persistente!',2),
(45,'A jornada da vida pode ser difícil, mas cada obstáculo superado nos torna mais fortes e sábios.',2),
(46,'Não tenha medo de falhar, pois é nas falhas que aprendemos e crescemos para alcançar o sucesso.',2),
(47,'A vida é uma tela em branco, cabe a você pintar o quadro mais colorido e significativo possível.',2),
(48,'A gratidão transforma o que temos em suficiente, e mais. Aprecie cada momento da sua vida.',2),
(49,'Inspire-se no presente, aprenda com o passado e construa o futuro que você deseja.',2),
(50,'Nunca subestime o impacto positivo que um simples ato de bondade pode ter na vida de alguém.',2),
(51,'Você não está sozinho. Deus está aqui para apoiá-lo em cada passo da jornada.',4),
(52,'É normal sentir-se perdido e sem esperança, mas lembre-se de que há luz no fim do túnel.',4),
(53,'Você é mais forte do que imagina, mesmo nos momentos mais difíceis.',4),
(54,'Não tenha medo de pedir ajuda. Aceitar o suporte de outras pessoas é um sinal de coragem.',4),
(55,'Cada dia é uma nova oportunidade para encontrar um pouco de paz e alívio.',4),
(56,'A jornada para a cura pode ser difícil, mas o importante é dar um passo de cada vez.',4),
(57,'Suas emoções são válidas. Dê-se permissão para sentir e expressar o que está dentro de você.',4),
(58,'Não se culpe por estar deprimido. A depressão é uma doença que pode ser tratada.',4),
(59,'Busque ajuda profissional. Um terapeuta ou psiquiatra pode fazer toda a diferença.',4),
(60,'Lembre-se: você não precisa enfrentar essa batalha sozinho. Existem pessoas dispostas a ajudar.',4),
(61,'Com Deus ao meu lado, não há desafio que eu não possa superar.',5),
(62,'Em meio às tribulações, encontrei em Cristo a paz que minha alma buscava.',5),
(63,'A fé em Deus é a luz que me guia nos momentos mais sombrios da vida.',5),
(64,'Deus nunca nos abandona, mesmo quando tudo parece estar desmoronando.',5),
(65,'Em Cristo encontrei o amor incondicional e a esperança que transformou minha vida.',5),
(66,'Nas mãos de Deus, encontrei refúgio e segurança para enfrentar os ventos da vida.',5),
(67,'Deus é o alicerce sólido em que construo minha vida e minha fé.',5),
(68,'Cristo é o caminho, a verdade e a vida. Nele encontro a direção que necessito.',5),
(69,'A presença de Deus é o conforto que acalma meu coração em momentos de angústia.',5),
(70,'Com Cristo em meu coração, sou mais forte para enfrentar os desafios que surgem.',5),
(71,'Com grandes poderes vêm grandes responsabilidades - Homem-Aranha',6),
(72,'Um herói pode ser qualquer pessoa. Até mesmo um homem fazendo algo tão simples e reconfortante como colocar um casaco em volta dos ombros de um garotinho para lembrá-lo que o mundo ainda não acabou - Batman',6),
(73,'O verdadeiro poder não se resume a força física, mas ao que você tem no coração - Capitão América',6),
(74,'Acredite em si mesmo, mesmo que ninguém mais acredite - Super-Homem',6),
(75,'Às vezes, a coragem é a quietude no meio do tumulto - Mulher Maravilha',6),
(76,'Nunca abaixe a cabeça, nunca desista, nunca pare de lutar - Thor',6),
(77,'Um herói de verdade não é medido pela quantidade de força que ele possui, mas sim pela força de seu coração - Homem de Ferro',6),
(78,'A verdadeira definição de um herói é alguém que faz o que deve ser feito, quando a situação exige, não importa as consequências - Wolverine',6),
(79,'Os verdadeiros heróis são aqueles que enfrentam o medo e a adversidade com coragem e compaixão - Mulher-Gato',6),
(80,'Não é o tamanho do herói que importa, mas o tamanho de seu coração - Homem-Formiga',6),
(81,'O dinheiro é uma ferramenta poderosa, use-o com sabedoria para construir seu futuro.',7),
(82,'A riqueza verdadeira não está apenas em acumular bens materiais, mas em apreciar as coisas simples da vida.',7),
(83,'A prosperidade começa com uma mentalidade positiva e uma visão clara de seus objetivos financeiros.',7),
(84,'O dinheiro pode ser um meio para atingir seus sonhos, mas não deve ser a única fonte de felicidade.',7),
(85,'Invista em conhecimento, pois ele é um dos ativos mais valiosos que você pode adquirir.',7),
(86,'A verdadeira riqueza está em ter paz de espírito e gratidão pelo que se tem.',7),
(87,'Seja responsável financeiramente, pois a liberdade vem da disciplina e do planejamento.',7),
(88,'O segredo para a riqueza está em criar múltiplas fontes de renda e diversificar seus investimentos.',7),
(89,'A verdadeira prosperidade começa quando você é capaz de ajudar os outros a conquistarem seus objetivos.',7),
(90,'A generosidade é uma das chaves para atrair mais abundância em sua vida.',7),
(91,'Bom dia! Aproveite cada momento deste novo dia com alegria e entusiasmo.',8),
(92,'Acorde com determinação e vá em busca dos seus sonhos. Hoje é uma nova oportunidade.',8),
(93,'Cada novo amanhecer é uma chance de recomeçar. Faça deste dia especial!',8),
(94,'Sorria para o mundo e o mundo sorrirá de volta para você. Tenha um dia radiante!',8),
(95,'Levante-se, estique os braços e diga para si mesmo: \"Hoje será um ótimo dia!\"',8),
(96,'Que a energia do sol ilumine seus passos e encha seu coração de positividade.',8),
(97,'Comece o dia com gratidão e o universo responderá com ainda mais motivos para agradecer.',8),
(98,'Cada novo dia é uma página em branco, escreva uma história incrível e memorável.',8),
(99,'Desperte sua alma e permita que a felicidade flua como o sol da manhã.',8),
(100,'Acredite em você e em todo o potencial que reside dentro de si. Hoje é o seu dia!',8),
(101,'O conhecimento é o tesouro mais valioso que você pode adquirir na vida.',9),
(102,'Estudar é a chave para desvendar as portas do futuro e alcançar seus sonhos.',9),
(103,'Cada hora de estudo é um investimento no seu próprio crescimento e sucesso.',9),
(104,'Não há limites para o que você pode aprender quando se dedica aos estudos.',9),
(105,'A mente é uma esponja sedenta por conhecimento. Alimente-a com livros e aprendizado.',9),
(106,'O estudo é a preparação para a jornada da vida. Quanto mais você se prepara, mais longe pode chegar.',9),
(107,'Os estudos não apenas abrem portas, mas também ampliam sua visão de mundo.',9),
(108,'A sabedoria nasce do estudo constante, assim como o rio é formado pelas gotas de água.',9),
(109,'Estudar é a ferramenta que vai moldar o seu futuro e criar oportunidades.',9),
(110,'O verdadeiro poder está na educação, e ela está disponível para quem busca conhecimento.',9),
(111,'A amizade é o abraço que o coração dá quando a alma precisa de carinho.',11),
(112,'Amigos são como estrelas: nem sempre os vemos, mas sabemos que estão sempre lá.',11),
(113,'Uma verdadeira amizade é um tesouro que brilha mesmo nas horas mais escuras.',11),
(114,'Os amigos são presentes da vida, embrulhados em laços de carinho e compreensão.',11),
(115,'Um amigo de verdade é aquele que conhece todas as suas histórias e ainda assim te ama.',11),
(116,'A amizade é como uma planta: precisa de cuidado, atenção e carinho para florescer.',11),
(117,'Um amigo é alguém que te conhece como ninguém e ainda te ama incondicionalmente.',11),
(118,'A verdadeira amizade não conhece distância, o tempo ou as circunstâncias.',11),
(119,'Ter um amigo ao lado faz os momentos felizes serem mais intensos e os tristes mais amenos.',11),
(120,'A amizade é a magia que acontece quando duas almas se reconhecem e se conectam.',11),
(121,'O amor é a base de um namoro sólido e o combustível que mantém o casamento vivo.',12),
(122,'O namoro é a fase da descoberta, o casamento é a eternidade da cumplicidade.',12),
(123,'Num bom relacionamento, a soma de duas pessoas é maior do que suas partes individuais.',12),
(124,'Casamento não é só encontrar a pessoa certa, mas ser a pessoa certa para o outro.',12),
(125,'Amar é encontrar a felicidade em cada gesto, em cada sorriso e em cada momento ao lado de quem se ama.',12),
(126,'Num relacionamento saudável, não existem disputas entre duas pessoas, mas sim uma parceria para enfrentar o mundo juntos.',12),
(127,'O namoro é o ensaio para o casamento, onde os corações aprendem a dançar em harmonia.',12),
(128,'O casamento é como uma dança, exige harmonia, sincronia e a disposição de seguir o mesmo ritmo.',12),
(129,'Nas adversidades da vida, o amor verdadeiro é o pilar que sustenta e fortalece o casal.',12),
(130,'Um namoro sólido é construído com confiança, respeito e uma boa dose de romantismo.',12)";

mysqli_query($con, $sql);

echo "OK";


?>